blog/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	url(r'^', include('core.urls', namespace="core")),

    url(r'^admin/', include(admin.site.urls)),
)

core/urls.py
from django.conf.urls import patterns, url

from .views import HomePageView, PostListView

urlpatterns = patterns('core.views',
    url(r'^$', HomePageView.as_view(), name='home'),
    url(r'^blog/$', PostListView.as_view(), name='blog'),
)

core/models.py
from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=500)
    slug = models.SlugField(editable=False)
    content = models.TextField()
    author = models.ForeignKey('auth.User')
    published = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True, editable=False)

core/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView

from .models import Post


class HomePageView(TemplateView):
	template_name = 'core/home.html'


class PostListView(ListView):
    model = Post

core/templates/base.html
<!DOCTYPE HTML>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Welcome!</title>

        <link href="{{ STATIC_URL }}css/bootstrap.min.css" rel="stylesheet">
        <link href="{{ STATIC_URL }}css/style.css" rel="stylesheet">

    </head>
    <body>
        <div class="container">
            
            <div class="row">
                <div class="col-md-10 col-md-offset-1">
                    <a class="link-hover" href="{% url 'core:home' %}"><h1>Breno Teixeira</h1></a>
                    <h3><small>Python, Django, Android and more!</small></h3>

                    <hr style="margin-bottom:0px">
                    <ul class="nav nav-pills nav-header">
                          <li><a href="{% url 'core:blog' %}">BLOG</a></li>
                          <li><a href="#">AUTHOR</a></li>
                          <li><a href="#">CONTACT</a></li>
                    </ul>
                    <hr style="margin:0px">
                </div>
            </div>

            <div class="row">
                <div class="col-md-8 col-md-offset-1">

                    {% block content %}
                    {% endblock content %}

                  <div class="text-center">
                    <ul class="pagination pagination-sm">
                      <li><a href="#">&laquo;</a></li>
                      <li><a href="#">1</a></li>
                      <li><a href="#">2</a></li>
                      <li><a href="#">3</a></li>
                      <li><a href="#">4</a></li>
                      <li><a href="#">5</a></li>
                      <li><a href="#">&raquo;</a></li>
                    </ul>
                  </div>

                </div>

                <aside class="col-md-2">

                <form style="padding:0px" class="navbar-form" role="search">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search" name="q">
                    <div class="input-group-btn">
                        <button style="height:34px" class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                    </div>
                </div>
                </form>

                  <div class="sidebar-module sidebar-module-inset">
                    <h5><strong>ABOUT ME</strong></h5>
                    <p style="font-family: Georgia, 'Times New Roman', Times, serif">Passionate and self-taught web developer interested in agile methods.</p>
                  </div>

                  <h5>CATEGORIES</h5>
                  <ul class="side-nav">
                    <li><a href="#">Python</a></li>
                    <li><a href="#">Django</a></li>
                    <li><a href="#">Design</a></li>
                    <li><a href="#">Android</a></li>
                  </ul>

                  <h5>ELSEWHERE</h5>
                  <ul class="side-nav">
                    <li><a href="https://www.facebook.com/breno.teixeira.98" target="blank">Facebook</a></li>
                    <li><a href="https://github.com/BrenoTeixeira" target="blank">GitHub</a></li>
                    <li><a href="https://twitter.com/Breno_tx" target="blank">Twitter</a></li>
                    <li><a href="https://www.linkedin.com/pub/breno-teixeira/47/b7b/917" target="blank">Linkedin</a></li>
                    <li><a href="https://google.com/+BrenoTeixeiraD" target="blank">Google+</a></li>
                  </ul>

                </aside>

            </div>

            <footer class="row">
                <div class="col-md-10 col-md-offset-1">
                    <hr>
                    <p>© Copyright 2014 - <a href="#">Breno Teixeira</a></p>
                </div>
            </footer>

        </div>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
        <script src="{{ STATIC_URL }}js/bootstrap.min.js"></script>
    </body>
</html>

core/templates/core/home.html
{% extends 'base.html' %}

core/templates/core/post_list.html
{% extends 'base.html' %}

{% block content %}

<article>

{% for post in post_list %}
<h3><a class="link-hover" href="#">{{ post.title }}</a></h3>

<h6>
    Written by
    <a href="#">
        {% if post.author.first_name %}
            {{ post.author.first_name }}
        {% else %}
            {{ post.author.username }}
        {% endif %}
    </a>
    on {{ post.created_at|date:'F d, o' }}.
</h6>

<div class="row">
    <div class="col-md-10">
        {{ post.content }}
        <br>
    </div>
</div>

</article>
<p>Tags:
    <a href="#"><span class="label label-info">Snipp</span></a>
    <a href="#"><span class="label label-info">Bootstrap</span></a>
    <a href="#"><span class="label label-info">UI</span></a>
    <a href="#"><span class="label label-info">growth</span></a>
    | <i class="icon-comment"></i> <a href="#">3 Comments</a>
    | <i class="icon-share"></i> <a href="#">39 Shares</a>
</p>

<hr>

{% empty %}
    <h4 class="text-center">There is no post yet.</h4>
{% endfor %}

{% endblock content %}